name: Release
on:
  push:
    branches: [main]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18.5.0
      - name: Git config
        run: |
          git config user.name ${{ secrets.CI_GITHUB_USER }}
          git config user.email ${{ secrets.CI_GITHUB_EMAIL }}
      - name: Install
        run: npm ci
      - name: Release
        run: npm run release
      - name: Push
        run: git push --follow-tags origin main
      - name: Update develop
        run: |
          git checkout develop
          git rebase main
          git push
