name: Release rc
on:
  push:
    branches: [develop]
jobs:
  release-rc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.5.0
      - name: Git config
        run: |
          git config user.name ${{ secrets.CI_GITHUB_USER }}
          git config user.email ${{ secrets.CI_GITHUB_EMAIL }}
      - name: Install
        run: npm ci
      - name: Release rc
        run: npm run release -- --prerelease rc
      - name: Push
        run: git push --follow-tags origin develop
